<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>SteamWalletChecker.ProgramWithAutoAuth</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SteamKit2" Version="3.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.1" />
  </ItemGroup>

</Project>
